export { default as About } from './About/About';
export { default as ContactUs } from './ContactUs/ContactUs';
export { default as Footer } from './Footer/Footer';
export { default as Header } from './Header/Header';
export { default as Hero } from './Hero/Hero';
export { default as GoogleReviews } from './GoogleReviews/GoogleReviews';
export { default as Orders } from './Orders/Orders';
export { default as Services } from './Services/Services';
export { default as WhyChooseUs } from './WhyChooseUs/WhyChooseUs';
